---
sensor:
  # Batterie volt
  - platform: adc
    pin: 33
    name: '${devicename} Battery Voltage'
    id: '${devicename}_voltage'
    attenuation: 11db
    unit_of_measurement: 'V'
    icon: 'mdi:battery-high'
    device_class: 'voltage'
    state_class: 'measurement'
    accuracy_decimals: 2
    filters:
      - multiply: 2
      # - calibrate_linear:
      #     # Map 0.0 (from sensor) to 0.0 (true value)
      #     - 0.0 -> 0.0
      #     - 5.0 -> 5.0
    update_interval: ${update_interval}

  # Battery %
  - platform: adc
    pin: 33
    name: '${devicename} Battery'
    id: '${devicename}_percent'
    attenuation: 11db
    accuracy_decimals: 2
    unit_of_measurement: '%'
    filters:
      - multiply: 2
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 2.50 -> 0.0
          - 4.20 -> 100.0
    update_interval: ${update_interval}
