---
deep_sleep:
  id: deep_sleep_control
  run_duration: ${run_duration}
  sleep_duration: ${sleep_duration}
  wakeup_pin:
    number: 35
    inverted: true
    allow_other_uses: true
    mode:
      input: true
      # pullup: true

# Wake Button
binary_sensor:
  - platform: gpio
    name: '${devicename} Wake Button'
    pin: 
      number: 35
      allow_other_uses: true
    internal: true
    setup_priority: 1000
