---
# Sensors for ESP version and WIFI information
text_sensor:
  # Installed version
  - platform: template
    name: '${devicename} - Installed version'
    icon: 'mdi:label-outline'
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 6h
  - platform: version
    hide_timestamp: true
    name: '${devicename} - ESPHome Version'

sensor:
  - platform: wifi_signal
    name: '${devicename} - WiFi Signal'
    update_interval: ${update_interval}
    icon: mdi:wifi-strength-1
