---
name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - LILYGO-T-Higrow-ESP32.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/yamllint.yml
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.file }}
  publish:
    needs: build
    name: Publish firmware
    uses: bruvv/workflows/.github/workflows/publish.yml@main
    with:
      files: LILYGO-T-Higrow-ESP32.yaml
      name: ESPHome Plant monitor
      manifest_filename: lilygo-t-higrow-manifest.json
      clean: false
