name: Repository Generated

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    permissions:
      issues: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create issue from setup checklist template
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Setup Checklist
          content-filepath: _template/setup-checklist.md
          assignees: ${{ github.repository_owner }}

      - name: Delete self
        run: rm -rf .github/workflows/repository-generated.yml
      - name: Remove template directory
        run: rm -rf _template

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Remove template files"
          git push
